apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: e4k-release
  namespace: flux-system
spec:
  releaseName: e4k
  targetNamespace: default
  chart:
    spec:
      chart: az-e4k
      sourceRef:
        kind: HelmRepository
        name: e4k-repo
      version: 0.1.0-amd64
  interval: 1m0s